name: Deploy raspberrypi
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: https://code.forgejo.org/actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Nix
        uses: https://github.com/cachix/install-nix-action@91a071959513ca103b54280ac0bef5b825791d4d # v31

      - name: Join Tailnet
        uses: https://github.com/tailscale/github-action@8688eb839e58e6b25c1ae96cd99d1c173299b842 # v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: latest

      - name: Build Nix Shell
        run: nix build .#devShells.x86_64-linux.ansible
      
      - name: Install Ansible Galaxy Dependencies
        run: nix develop .#ansible --command ansible-galaxy install -r ansible/requirements.yml
      
      - name: Write Ansible Vault Password to file
        run: echo '${{ secrets.ANSIBLE_VAULT_PASSWORD }}' > $HOME/vault-password

      - name: Deploy with Ansible
        run: nix develop .#ansible --command bash -c 'ansible-playbook ansible/raspberrypi.yml --vault-password-file "$HOME/vault-password" -i ansible/inventory.yaml'
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
