name: NixOS config diff
on:
  pull_request:
jobs:
  diff:
    name: Diff ${{ matrix.configuration }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - "artemis"
          - "gitlabber"
          - "marie-desktop"
    steps:
      - name: Install Nix
        uses: https://github.com/cachix/install-nix-action@v29
        with:
          extra_nix_config: |
            extra-substituters = https://uwumarie.cachix.org
            extra-trusted-public-keys = uwumarie.cachix.org-1:H6nX8e82pu2GQ8CGU3j1qHTG7QMYzZ15oSBh26XhtVo=

      - name: Start SSH Agent
        uses: https://github.com/webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}
      
      - name: Add git.marie.cologne's ssh host key
        run: echo "git.marie.cologne ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAFQjqgMtqrMy7AKCQN4aMZitASg9MWEP1u6lfVdA0v8" >> ~/.ssh/known_hosts

      - name: Post NixOS config diff
        uses: https://github.com/NyCodeGHG/nixos-diff-action@forgejo-actions
        with:
          configuration: ${{ matrix.configuration }}
