name: Update NVIDIA driver
on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1'

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Nix
        uses: https://github.com/cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            extra-substituters = https://uwumarie.cachix.org
            extra-trusted-public-keys = uwumarie.cachix.org-1:H6nX8e82pu2GQ8CGU3j1qHTG7QMYzZ15oSBh26XhtVo=
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run nvidia update script
        run: ./scripts/update-nvidia.sh

      - name: Create Pull Request
        uses: https://github.com/peter-evans/create-pull-request@v7.0.1
        with:
          committer: Forgejo Actions <noreply@forgejo.org>
          branch: update-nvidia-driver
          title: Update nvidia driver
          reviewers: marie

