name: Check Terraform
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: https://code.forgejo.org/actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Nix
        uses: https://github.com/cachix/install-nix-action@91a071959513ca103b54280ac0bef5b825791d4d # v31
      
      - name: tofu init
        run: nix shell --inputs-from . nixpkgs#opentofu --command tofu init
        working-directory: infra

      - name: tofu validate
        run: nix shell --inputs-from . nixpkgs#opentofu --command tofu validate
        working-directory: infra
