[
  ./applications/fail2ban.nix
  ./applications/nginx.nix
  ./applications/nix.nix
  ./applications/openssh.nix
  ./applications/prismlauncher.nix
  ./applications/tailscale.nix
  ./applications/valkey.nix
  ./applications/tools.nix
  ./system/audio.nix
  ./system/base.nix
  ./system/dns.nix
  ./system/graphical.nix
  ./system/headless.nix
  ./system/locale.nix
  ./system/nspawn.nix
  ./system/ntp.nix
  ./system/upgrade-diff.nix
  ./system/zram.nix
  ./users/marie.nix
]
