[
  ./applications/fail2ban.nix
  ./applications/nginx.nix
  ./applications/nix.nix
  ./applications/openssh.nix
  ./system/base.nix
  ./system/acme.nix
  ./system/locale.nix
  ./system/nspawn.nix
  ./users/marie.nix
  ./system/upgrade-diff.nix
]
