[
  ./programs/eza.nix
  ./programs/git.nix
  ./programs/jujutsu.nix
  ./programs/ripgrep.nix
  ./programs/ssh.nix
  ./programs/starship.nix
  ./programs/unlock-ssh-keys.nix
  ./programs/zsh.nix
  ./programs/tmux.nix
]
