[
  ./programs/eza.nix
  ./programs/fish.nix
  ./programs/git.nix
  ./programs/jujutsu.nix
  ./programs/ssh.nix
  ./programs/tmux.nix
  ./programs/zsh.nix
  ./programs/emacs.nix
  ./programs/bat.nix
]
