- name: Setup Caddy
  become: true
  hosts: all
  vars:
    cloudflare_token: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      30363630656132653233383263643931636236616361353737623961316434666131386239643135
      3539646464653335623630333533613462373766636461300a373531306261643431326335373365
      61373065376465343432666238656635356438356265313662363334363632336633643230373830
      6234666661323464340a373334343064663265613136616263666366656437623861643462323762
      62313262346561396661646235373435383231313234386464393261643539636431306462386265
      3534623263653338316263373337633731366135656562303963
    token_file_path: /etc/caddy/cf-token
    dropin_location: /etc/systemd/system/caddy.service.d/10-cf-token.conf
  pre_tasks:
    - name: Create {{ token_file_path | dirname }}
      ansible.builtin.file:
        path: "{{ token_file_path | dirname }}"
        state: directory
        owner: www-data
        group: root
        mode: "770"
    - name: Write cloudflare token credential
      ansible.builtin.copy:
        dest: "{{ token_file_path }}"
        owner: root
        group: root
        mode: "600"
        content: "{{ cloudflare_token }}"
    - name: Create {{ dropin_location | dirname }}
      ansible.builtin.file:
        path: "{{ dropin_location | dirname }}"
        state: directory
        owner: root
        group: root
        mode: "755"
    - name: Create systemd dropin for credential
      register: systemd_dropin
      ansible.builtin.template:
        dest: "{{ dropin_location }}"
        owner: root
        group: root
        mode: "664"
        src: ./10-cf-token.conf.j2
      notify:
        - Reload systemd
  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
  roles:
    - role: caddy_ansible.caddy_ansible
      caddy_config: "{{ lookup('template', './Caddyfile') }}"
      caddy_version: "2.10.0"
      caddy_systemd_capabilities_enabled: true
      caddy_packages:
        - "github.com/caddy-dns/cloudflare"
