name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 14 * * 5' # runs weekly on Sunday at 00:00

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@6004951b182f8860210c8d6f0d808ec5b1a33d28 # v25
      - uses: cachix/cachix-action@v14
        with:
          name: uwumarie
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "flake: update inputs" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
